### ISSUE TITLE
RTBKit runs on Mac OS X 

### ISSUE THREAD

**Issue by rchau73** [rtbkit/rtbkit#272]
Does anybody know if for learning purposes only is posible to compile and run RTB Kit on MAC OS X El Captain version ?

If so, what are the enviroment setup to compile the RTB kit ?

Thanks.

**Comment by skaag** [comment]
I honestly recommend you run it within a VM, for the following reasons:

- It's seriously complex to get it to run on OSX because of the various dependencies
- It's really simple to run a VM in OSX (VBOX + Vagrant)
- It mimics your production environment (nobody will run rtbkit on OSX in production)

**Comment by rchau73** [comment]
Thanks, I will use VBOX + Vagrant.
