### ISSUE TITLE
Error on Protobuf ubuntu 14

### ISSUE THREAD

**Issue by RajibHossen** [rtbkit/rtbkit#291]
I am getting error in make compile NODEJS_ENABLED=0 steps. I am using ubuntu 14.04.
> 
> [PBUF c++] rtbkit/plugins/exchange/realtime-bidding.proto
> /bin/bash: protoc: command not found
> make: *** [build/x86_64/gen/rtbkit/plugins/exchange/realtime-bidding.pb.cc] Error 127

**Comment by mikeburkat** [comment]
Seems like protobuf is missing on your installation. Most likely problem would be that when you compiled rtbkit-deps protobuf did not compile successfully. 
You can know that it might of failed if your $HOME/local/bin does not contain `protoc`.
You can try going back to your rtbkit-deps folder and executing `make install_protobuf` and let me know if there was an error there, and what the error is.

Otherwise there may be a problem with your $PATH. you can check that $HOME/local/bin is in your $PATH environment variable.

**Comment by RajibHossen** [comment]
In $HOME/local/bin, 
```
$ protoc --version
libprotoc 2.4.2
```
but inside rtbkit 
```
$ protoc --version
The program 'protoc' is currently not installed. You can install it by typing:
sudo apt-get install protobuf-compiler
````
I also follow your command make install_protobuf inside rtbkit-deps
Here's the out of environment PATH
````
$ env | grep PATH
LD_LIBRARY_PATH=/home/rajib/local/lib:
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
PATH=/home/rajib/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
PKG_CONFIG_PATH=/home/rajib/local/lib/pkgconfig/:/home/rajib/local/lib/pkg-config/
```

**Comment by RajibHossen** [comment]
I resolved it. In the getting started section, setting environment variable was session based. So in rtbkit repo, the variable was not found.  Then I set environment variable inside rtbkit and it works.
